# source ~/Documents/dotfiles/bash/bashrc
export GOPRIVATE=github.com/mantix4
export EDITOR=nvim
alias vim=nvim
export PATH=$PATH:~/.local/teleport

function kittyInstall {
	if [[ -z "$@" ]]
	then
		cat <<EOF>&2
Usage: kittyInstall {ssh host}
Example: kittyInstall ssh sduran@thinkpad.lan
         kittyInstall tsh ssh root@m4sensor

EOF
	return
	fi
	infocmp -a xterm-kitty | tic -x /dev/stdin | $@ "cat > ~/.terminfo"
}
eval "$(~/.local/bin/mise activate bash)"

function fix_ssh_auth
{
  eval "export $(tmux show-env | grep ^SSH_AUTH_SOCK=)"
}

