# source ~/Documents/dotfiles/bash/bashrc
export GOPRIVATE=github.com/mantix4
export EDITOR=nvim
alias vim=nvim
export PATH=$PATH:~/.local/teleport

function kittyInstallTermcap {
	if [[ -z "$@" ]]
	then
		cat <<EOF>&2
Usage: kittyInstall {ssh host}
Example: kittyInstall ssh sduran@thinkpad.lan
         kittyInstall tsh ssh root@m4sensor

EOF
	return
	fi
	infocmp -a xterm-kitty | tic -x /dev/stdin | $@ "mkdir -p ~/.terminfo/x && cat > ~/.terminfo/x/xterm-kitty"
}
eval "$(~/.local/bin/mise activate bash)"

function tmux_fix_env
{
  eval "export $(tmux show-env | grep '^\(SSH_AUTH_SOCK\|DISPLAY\)=')"
}

