# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"logseq" = ""
"github" = ""
"discord" = ""
"signal" = ""
"tieneinfo mail" = ""
"webmail" = ""
"twitch" = ""
"whatsapp" = ""
"nvim" = ""
"vim" = ""
"alacritty" = ""
"kitty" = ""
"github" = ""
"rust" = ""
"google" = ""
"private browsing" = ""
"chrome" = ""
"file manager" = ""
"nemo" = ""
"nautilus" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"gthumb" = ""
"menu" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"disk usage" = ""
".pdf" = ""
"firefox" = ""
"firefox-esr" = ""
"clock" = ""

[other]
fallback_icon = ""
deduplicate_icons = false
